top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/mappers
builddir     = /home/zhongyj/httpd-2.2.24/modules/mappers
VPATH        = /home/zhongyj/httpd-2.2.24/modules/mappers

include $(top_srcdir)/build/special.mk

