top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/metadata
builddir     = /home/zhongyj/httpd-2.2.24/modules/metadata
VPATH        = /home/zhongyj/httpd-2.2.24/modules/metadata

include $(top_srcdir)/build/special.mk

