top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/loggers
builddir     = /home/zhongyj/httpd-2.2.24/modules/loggers
VPATH        = /home/zhongyj/httpd-2.2.24/modules/loggers

include $(top_srcdir)/build/special.mk

