top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/generators
builddir     = /home/zhongyj/httpd-2.2.24/modules/generators
VPATH        = /home/zhongyj/httpd-2.2.24/modules/generators

include $(top_srcdir)/build/special.mk

