top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/echo
builddir     = /home/zhongyj/httpd-2.2.24/modules/echo
VPATH        = /home/zhongyj/httpd-2.2.24/modules/echo

include $(top_srcdir)/build/special.mk

