top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/filters
builddir     = /home/zhongyj/httpd-2.2.24/modules/filters
VPATH        = /home/zhongyj/httpd-2.2.24/modules/filters

include $(top_srcdir)/build/special.mk

