top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/experimental
builddir     = /home/zhongyj/httpd-2.2.24/modules/experimental
VPATH        = /home/zhongyj/httpd-2.2.24/modules/experimental
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
