top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/aaa
builddir     = /home/zhongyj/httpd-2.2.24/modules/aaa
VPATH        = /home/zhongyj/httpd-2.2.24/modules/aaa

include $(top_srcdir)/build/special.mk

