top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/cache
builddir     = /home/zhongyj/httpd-2.2.24/modules/cache
VPATH        = /home/zhongyj/httpd-2.2.24/modules/cache

include $(top_srcdir)/build/special.mk

