top_srcdir   = /home/zhongyj/httpd-2.2.24
top_builddir = /home/zhongyj/httpd-2.2.24
srcdir       = /home/zhongyj/httpd-2.2.24/modules/http
builddir     = /home/zhongyj/httpd-2.2.24/modules/http
VPATH        = /home/zhongyj/httpd-2.2.24/modules/http

include $(top_srcdir)/build/special.mk

